import redvelvet from "@/assets/products/cake-redvelvet.jpg";
import tiramisu from "@/assets/products/cake-tiramisu.jpg";
import butterscotch from "@/assets/products/cake-butterscotch.jpg";
import cake2 from "@/assets/products/cake 2.webp";
import cake3 from "@/assets/products/cake3.webp";
import cake4 from "@/assets/products/cake 4.webp";
import cake5 from "@/assets/products/cake 5.webp";
import cake6 from "@/assets/products/cake 6.webp";
import cake8 from "@/assets/products/cake 8.webp";
import cake9 from "@/assets/products/cake9.webp";
import cake10 from "@/assets/products/cake 10.jpg";
import cake11 from "@/assets/products/cake 11.webp";
import cake12 from "@/assets/products/cake 12.webp";
import cake13 from "@/assets/products/cake 13.webp";
import cake15 from "@/assets/products/cake 15.webp";
import cake16 from "@/assets/products/cake 16.webp";
import cake18 from "@/assets/products/cake 18.webp";
import cake21 from "@/assets/products/cake 21.webp";
import cake23 from "@/assets/products/cake 23.webp";
import cake from "@/assets/products/cake.webp";
import cake6b from "@/assets/products/cake6.webp";
import cakeke from "@/assets/products/cakeke.webp";
import assortedCake from "@/assets/products/multiple type of cake.webp";
import bite from "@/assets/products/bite.webp";
import cakeBite from "@/assets/products/cake bite 1.webp";
import cookiesImg from "@/assets/products/cookies.webp";
import cookie2 from "@/assets/products/cookie2.webp";
import coldCoffee from "@/assets/products/desi cold coffee.webp";
import drink from "@/assets/products/drink.webp";
import mangoTrifle from "@/assets/products/mongo vanulla trifle dessert bowl.webp";
import kunafa from "@/assets/products/traditional kunafa.webp";
import bakedBlueberry from "@/assets/Baked Cheesecake Slices Blueberry.jpg";
import biscoffCheesecake from "@/assets/BiscoffCheesecake Slices.jpg";
import blackForest from "@/assets/Black Forest Cake —.jpg";
import blueberryCake from "@/assets/Blueberry Cake —.jpg";
import cadburyCake from "@/assets/Cadbury Cake —.jpg";
import caramelBaked from "@/assets/Caramel Baked Cheesecake Slices.jpg";
import casattaCake from "@/assets/Casatta Cake.jpg";
import chocoTruffle from "@/assets/Chocolate Truffle Cake.jpg";
import chocolavaImg from "@/assets/Chocolava —.jpeg";
import ferreroCake from "@/assets/Ferrero Rocher Cake.jpg";
import frozenBiscoff from "@/assets/Frozen Cheesecake Slices Biscoff.jpg";
import frozenBlueberry from "@/assets/Frozen Cheesecake Slices Blueberry.jpg";
import frozenCaramel from "@/assets/Frozen Cheesecake Slices Caramel.jpg";
import frozenMango from "@/assets/Frozen Cheesecake Slices Mango.jpg";
import frozenNutella from "@/assets/Frozen Cheesecake Slices Nutella.jpg";
import gulkandImg from "@/assets/Gulkand Cak.jpg";
import kitkatCake from "@/assets/Kitkat Cake —.jpg";
import mangoCheesecake from "@/assets/Mango Cheesecake Slices.jpg";
import mangoKunafaBowl from "@/assets/Mango Desserts Mango Kunafa Bowl.jpg";
import mangoTub from "@/assets/Mango Desserts Mango Tub Cake.jpg";
import mangoPudding from "@/assets/Mango DessertsMango Pudding.jpg";
import mangoShake from "@/assets/Mango Shake drink.jpg";
import nutellaBaked from "@/assets/Nutella Baked Cheesecake Slices.jpg";
import pineappleCake from "@/assets/Pinapple Cake.jpg";
import strawberryCake from "@/assets/Strawberry.jpg";
import strawberryBaked from "@/assets/strawberry Baked Cheesecake Slices.jpg";
import tresLechesMango from "@/assets/Tres Leches Cake Alphonso Mango.jpg";
import tresLechesRose from "@/assets/Tres Leches Cake Rose Per Slice).jpg";
import tresLechesThandai from "@/assets/Tres Leches Cake Thandai Per Slice).jpg";
import vanillaCake from "@/assets/Vanilla Cake.jpg";
import vanillaOreo from "@/assets/Vanilla Waffle  With Oreo —.jpg";
import vanillaWhite from "@/assets/Vanilla Waffle With White Chocolate.jpg";
import vanillaDark from "@/assets/With Dark Chocolate Vanilla Waffle.jpg";
import vanillaKitkat from "@/assets/With KitKat Vanilla Waffle.jpg";
import vanillaMilk from "@/assets/With Milk Chocolate.jpg";
import vanillaTriple from "@/assets/With Triple Chocolate.jpg";
import biscoffKunafa from "@/assets/products/Biscoff kunafa.jpg";
import brownieBowl from "@/assets/Brownie Bowl — 1.jpg";
import brownieChoc from "@/assets/Brownie with Milk Chocolate Bowl.jpg";
import blueberryKunafa from "@/assets/products/Kunafa Blueberry.jpg";
import chocolateKunafa from "@/assets/products/Kunafa Chocolate.webp";
import nutellaKunafa from "@/assets/products/Kunafa Nutella.jpg";
import pistaBrownie from "@/assets/products/Kunafa Pista Brownie.jpg";
import classicKunafa from "@/assets/products/Kunafa-3 clasic.webp";
import nutellaBrownie from "@/assets/Special Brownie with Triple Chocolate Bowl.jpg";
import nutellaKunafaBrownie from "@/assets/Special Brownie Kunafa with Hezelnut Bowl.jpg";
import sizzlerBrownie from "@/assets/Special Sizzler Brownie Scoop.jpg";
import strawberryKunafa from "@/assets/products/StrawberryKunafa.jpg";
import tripleBrownieBowl from "@/assets/products/Triple Chocolate Brownie Bowl —.jpg";
import heroCake from "@/assets/hero-cake.jpg";


export type MenuItem = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  note: string;
  image: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  delivery: "Today" | "Tomorrow";
  eggless: boolean;
  flavours: string[];
  weights: string[];
  occasions: string[];
  badges: string[];
  bestSeller?: boolean;
  newArrival?: boolean;
};

export const categoryOptions = [
  { slug: "all", label: "All Products" },
  { slug: "cakes", label: "Cakes" },
  { slug: "cupcakes", label: "Cupcakes" },
  { slug: "cookies", label: "Cookies" },
  { slug: "waffles", label: "Waffles" },
  { slug: "brownies", label: "Brownies" },
  { slug: "kunafa", label: "Kunafa" },
  { slug: "cheesecakes", label: "Cheesecakes" },
  { slug: "tres-leches", label: "Tres Leches" },
  { slug: "mango-desserts", label: "Mango Desserts" },
  { slug: "desserts", label: "Desserts" },
  { slug: "pastries", label: "Pastries" },
  { slug: "beverages", label: "Beverages" },
];

export const flavourOptions = ["Chocolate", "Vanilla", "Red Velvet", "Butterscotch", "Coffee", "Fruit", "Caramel", "Berry"];
export const weightOptions = ["0.5 kg", "1 kg", "1.5 kg", "2 kg", "3 kg", "Pack of 3", "Pack of 6"];
export const occasionOptions = ["Birthday", "Anniversary", "Wedding", "Kids", "Celebration"];
export const quickPicks = [
  { slug: "best-seller", label: "Best Seller" },
  { slug: "new", label: "New Arrival" },
  { slug: "discounted", label: "Discounted" },
  { slug: "today", label: "Delivery Today" },
  { slug: "stock", label: "In Stock Only" },
];

const base = {
  price: 0,
  mrp: 0,
  rating: 4.8,
  reviews: 100,
  delivery: "Today" as const,
  eggless: false,
  flavours: [] as string[],
  weights: [] as string[],
  occasions: [] as string[],
  badges: [] as string[],
};

export const menuItems: MenuItem[] = [
  {
    ...base,
    slug: "ferrero-hazelnut-cake",
    name: "Ferrero Rocher Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Roasted hazelnut crunch, ganache drip",
    image: ferreroCake,
    price: 1150,
    mrp: 1150,
    rating: 5.0,
    reviews: 512,
    flavours: ["Chocolate"],
    weights: ["1 kg", "1.5 kg", "2 kg", "3 kg"],
    occasions: ["Birthday", "Anniversary", "Wedding", "Celebration"],
    badges: ["Best Seller", "Limited Edition"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "chocolate-truffle-cake",
    name: "Chocolate Truffle Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Belgian ganache, silk-soft sponge",
    image: chocoTruffle,
    price: 650,
    mrp: 650,
    rating: 4.9,
    reviews: 428,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Best Seller", "Chef Special"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "black-forest-cake",
    name: "Black Forest Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Kirsch cherries, dark chocolate flakes",
    image: blackForest,
    price: 500,
    mrp: 500,
    rating: 4.8,
    reviews: 376,
    delivery: "Tomorrow",
    flavours: ["Chocolate", "Fruit"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "red-velvet-cherry-cake",
    name: "Red Velvet Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Cream cheese clouds, morello cherries",
    image: redvelvet,
    price: 500,
    mrp: 500,
    rating: 4.8,
    reviews: 312,
    eggless: true,
    flavours: ["Red Velvet"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Anniversary", "Kids"],
    badges: ["Trending", "Fresh Today"],
  },
  {
    ...base,
    slug: "tiramisu-cake",
    name: "Classic Tiramisu",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Espresso soak, mascarpone velvet",
    image: tiramisu,
    price: 999,
    mrp: 1199,
    rating: 4.8,
    reviews: 231,
    flavours: ["Coffee"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Anniversary", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "butterscotch-praline-cake",
    name: "Butterscotch Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Golden caramel drip, praline crunch",
    image: butterscotch,
    price: 400,
    mrp: 400,
    rating: 4.7,
    reviews: 208,
    eggless: true,
    flavours: ["Butterscotch", "Caramel"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Eggless", "100% Handmade"],
  },
  {
    ...base,
    slug: "blueberry-cheesecake",
    name: "Blueberry Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Baked New York style, wild berries",
    image: blueberryCake,
    price: 650,
    mrp: 650,
    rating: 4.9,
    reviews: 189,
    flavours: ["Fruit"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Anniversary", "Wedding", "Celebration"],
    badges: ["Chef Special", "Limited Edition"],
  },

  {
    ...base,
    slug: "classic-vanilla-dream",
    name: "Vanilla Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Madagascar vanilla sponge with mascarpone cream",
    image: vanillaCake,
    price: 400,
    mrp: 400,
    rating: 4.8,
    reviews: 356,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "rose-petal-delight",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Floral buttercream, delicate rose drizzle",
    image: cake2,
    price: 899,
    mrp: 1149,
    rating: 4.8,
    reviews: 187,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "cream-cascade-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Soft cream layers with a glossy cascade",
    image: cake3,
    price: 799,
    mrp: 999,
    rating: 4.7,
    reviews: 124,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "choco-drip-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Rich chocolate drip over silky sponge",
    image: cake4,
    price: 999,
    mrp: 1249,
    rating: 4.9,
    reviews: 268,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Best Seller", "Chef Special"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "berry-bloom-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Fresh berries crowned on vanilla cream",
    image: cake5,
    price: 1099,
    mrp: 1399,
    rating: 4.8,
    reviews: 156,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "buttercream-bliss-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Whipped buttercream, soft vanilla base",
    image: cake6,
    price: 899,
    mrp: 1099,
    rating: 4.8,
    reviews: 143,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "caramel-crown-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Golden caramel glaze with a rich base",
    image: cake8,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 98,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "velvet-swirl-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Marbled swirl finish on cream layers",
    image: cake9,
    price: 849,
    mrp: 1049,
    rating: 4.7,
    reviews: 112,
    flavours: ["Vanilla", "Berry"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "silk-cake-classic",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Feather-light sponge with silk icing",
    image: cake10,
    price: 799,
    mrp: 999,
    rating: 4.7,
    reviews: 176,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Eggless", "Fresh Today"],
  },
  {
    ...base,
    slug: "frosted-fancy-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Piped frosting, party-perfect finish",
    image: cake12,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 88,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "royal-rose-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Rose-topped elegance in soft pastels",
    image: cake13,
    price: 1149,
    mrp: 1449,
    rating: 4.9,
    reviews: 76,
    eggless: true,
    flavours: ["Vanilla", "Berry"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Anniversary", "Wedding", "Celebration"],
    badges: ["Signature", "Chef Special"],
  },
  {
    ...base,
    slug: "swirl-dream-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Tall cream swirls, soft baked layers",
    image: cake15,
    price: 899,
    mrp: 1099,
    rating: 4.7,
    reviews: 94,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "hazelnut-paradise-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Nutty crunch with a smooth choco glaze",
    image: cake16,
    price: 1049,
    mrp: 1299,
    rating: 4.8,
    reviews: 118,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "choco-nut-delight",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Belgian chocolate with toasted nuts",
    image: cake18,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 202,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "petite-cake-slice",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Custom design cake, baked to order",
    image: heroCake,
    price: 199,
    mrp: 249,
    rating: 4.7,
    reviews: 240,
    eggless: true,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "berry-cheer-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Berry-dotted buttercream, bright finish",
    image: cake21,
    price: 999,
    mrp: 1249,
    rating: 4.8,
    reviews: 86,
    flavours: ["Berry", "Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "confetti-fun-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Celebration sprinkles on vanilla cream",
    image: cake23,
    price: 899,
    mrp: 1099,
    rating: 4.7,
    reviews: 74,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "bakers-choice-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "The counter favourite, baked fresh daily",
    image: cake,
    price: 899,
    mrp: 1099,
    rating: 4.8,
    reviews: 321,
    eggless: true,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Best Seller", "100% Handmade"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "double-choco-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Two-layer cocoa indulgence, glossy top",
    image: cake6b,
    price: 979,
    mrp: 1229,
    rating: 4.8,
    reviews: 145,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "house-special-cake",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Signature recipe, creamy and light",
    image: cakeke,
    price: 949,
    mrp: 1149,
    rating: 4.8,
    reviews: 98,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Signature"],
  },
  {
    ...base,
    slug: "celebration-assortment",
    name: "Custom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "A platter of our finest designs to share",
    image: assortedCake,
    price: 1499,
    mrp: 1899,
    rating: 4.9,
    reviews: 210,
    flavours: ["Vanilla", "Chocolate", "Fruit"],
    weights: ["2 kg"],
    occasions: ["Birthday", "Celebration", "Wedding"],
    badges: ["Best Seller", "Limited Edition"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "pineapple-cake",
    name: "Pinapple Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Fresh pineapple chunks with soft cream layers",
    image: pineappleCake,
    price: 400,
    mrp: 400,
    rating: 4.7,
    reviews: 118,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "strawberry-cake",
    name: "Strawberry Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Juicy strawberries folded into silky cream",
    image: strawberryCake,
    price: 400,
    mrp: 400,
    rating: 4.7,
    reviews: 96,
    eggless: true,
    flavours: ["Berry", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids", "Anniversary"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "mix-fruit-cake",
    name: "Mix Fruit Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "A medley of fresh fruits in light cream",
    image: cake11,
    price: 500,
    mrp: 500,
    rating: 4.7,
    reviews: 104,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Fresh Daily", "Eggless"],
  },
  {
    ...base,
    slug: "casatta-cake",
    name: "Casatta Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Classic layered casatta with fruity sponge",
    image: casattaCake,
    price: 500,
    mrp: 500,
    rating: 4.6,
    reviews: 47,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "gulkand-cake",
    name: "Gulkand Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Rose gulkand layers with floral cream",
    image: gulkandImg,
    price: 500,
    mrp: 500,
    rating: 4.8,
    reviews: 63,
    eggless: true,
    flavours: ["Vanilla", "Berry"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Anniversary", "Celebration"],
    badges: ["Exotic", "Eggless"],
  },
  {
    ...base,
    slug: "kitkat-cake",
    name: "Kitkat Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Kitkat fenced cake loaded with gems",
    image: kitkatCake,
    price: 950,
    mrp: 950,
    rating: 4.8,
    reviews: 197,
    flavours: ["Chocolate"],
    weights: ["1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Exotic", "Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "cadbury-cake",
    name: "Cadbury Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Cadbury overloaded with silky chocolate cream",
    image: cadburyCake,
    price: 950,
    mrp: 950,
    rating: 4.8,
    reviews: 173,
    flavours: ["Chocolate"],
    weights: ["1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Anniversary", "Celebration"],
    badges: ["Exotic"],
  },
  {
    ...base,
    slug: "berry-bliss-cupcakes",
    name: "Berry Bliss Cupcakes",
    category: "Cupcakes",
    categorySlug: "cupcakes",
    note: "Vanilla bean cupcakes, mixed-berry swiss meringue",
    image: bite,
    price: 220,
    mrp: 260,
    rating: 4.8,
    reviews: 96,
    flavours: ["Vanilla", "Berry"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "mini-cake-bites",
    name: "Mini Cake Bites",
    category: "Cupcakes",
    categorySlug: "cupcakes",
    note: "Bite-sized bakes with silky cream tops",
    image: cakeBite,
    price: 299,
    mrp: 349,
    rating: 4.7,
    reviews: 84,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["New", "Fresh Daily"],
    newArrival: true,
  },
  {
    ...base,
    slug: "salted-caramel-cookie",
    name: "Salted Caramel Cookie",
    category: "Cookies",
    categorySlug: "cookies",
    note: "Chewy centre, crisp edges, gooey caramel",
    image: cookie2,
    price: 120,
    mrp: 150,
    rating: 4.7,
    reviews: 140,
    flavours: ["Chocolate", "Caramel"],
    weights: ["Pack of 3"],
    occasions: ["Kids", "Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "classic-cookie-box",
    name: "Classic Cookie Box",
    category: "Cookies",
    categorySlug: "cookies",
    note: "Buttery classics, baked golden and crisp",
    image: cookiesImg,
    price: 349,
    mrp: 420,
    rating: 4.8,
    reviews: 165,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "mango-vanilla-trifle",
    name: "Mango Vanilla Trifle",
    category: "Desserts",
    categorySlug: "desserts",
    note: "Layered mango, vanilla cream and sponge",
    image: mangoTrifle,
    price: 349,
    mrp: 420,
    rating: 4.8,
    reviews: 92,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["Pack of 1"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Fresh Daily", "Eggless"],
  },
  {
    ...base,
    slug: "classic-kunafa",
    name: "Classic Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Crispy semolina, sweet cheese pull, syrup · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: classicKunafa,
    price: 100,
    mrp: 100,
    rating: 4.9,
    reviews: 78,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 Slice"],
    occasions: ["Celebration"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "desi-cold-coffee",
    name: "Desi Cold Coffee",
    category: "Beverages",
    categorySlug: "beverages",
    note: "Frothy, chilled, slow-brewed classic",
    image: coldCoffee,
    price: 80,
    mrp: 80,
    rating: 4.8,
    reviews: 210,
    flavours: ["Coffee"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily", "Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "signature-cold-drink",
    name: "Signature Cold Drink",
    category: "Beverages",
    categorySlug: "beverages",
    note: "House blend iced treat, served chilled",
    image: drink,
    price: 80,
    mrp: 80,
    rating: 4.7,
    reviews: 134,
    flavours: ["Coffee", "Vanilla"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["New"],
    newArrival: true,
  },
  /* ----- Frozen Cheesecake Slices ----- */
  {
    ...base,
    slug: "frozen-blueberry-cheesecake-slice",
    name: "Frozen Blueberry Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Chilled blueberry cheesecake slice",
    image: frozenBlueberry,
    price: 100,
    mrp: 100,
    rating: 4.8,
    reviews: 64,
    eggless: true,
    flavours: ["Berry"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Frozen", "Fresh Daily"],
  },
  {
    ...base,
    slug: "frozen-nutella-cheesecake-slice",
    name: "Frozen Nutella Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Chilled nutella cheesecake slice",
    image: frozenNutella,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 71,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Frozen"],
  },
  {
    ...base,
    slug: "frozen-biscoff-cheesecake-slice",
    name: "Frozen Biscoff Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Chilled biscoff cheesecake slice",
    image: frozenBiscoff,
    price: 129,
    mrp: 129,
    rating: 4.9,
    reviews: 49,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Frozen", "Trending"],
  },
  {
    ...base,
    slug: "frozen-mango-cheesecake-slice",
    name: "Frozen Mango Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Chilled mango cheesecake slice",
    image: frozenMango,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 43,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Frozen"],
  },
  {
    ...base,
    slug: "frozen-caramel-cheesecake-slice",
    name: "Frozen Caramel Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Chilled caramel cheesecake slice",
    image: frozenCaramel,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 39,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Frozen"],
  },
  /* ----- Baked Cheesecake Slices ----- */
  {
    ...base,
    slug: "baked-blueberry-cheesecake-slice",
    name: "Baked Blueberry Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked blueberry cheesecake slice",
    image: bakedBlueberry,
    price: 149,
    mrp: 149,
    rating: 4.8,
    reviews: 82,
    eggless: true,
    flavours: ["Berry"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked", "Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "baked-strawberry-cheesecake-slice",
    name: "Baked Strawberry Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked strawberry cheesecake slice",
    image: strawberryBaked,
    price: 149,
    mrp: 149,
    rating: 4.8,
    reviews: 76,
    eggless: true,
    flavours: ["Berry"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked"],
  },
  {
    ...base,
    slug: "baked-nutella-cheesecake-slice",
    name: "Baked Nutella Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked nutella cheesecake slice",
    image: nutellaBaked,
    price: 169,
    mrp: 169,
    rating: 4.9,
    reviews: 88,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked", "Trending"],
  },
  {
    ...base,
    slug: "baked-biscoff-cheesecake-slice",
    name: "Baked Biscoff Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked biscoff cheesecake slice",
    image: biscoffCheesecake,
    price: 169,
    mrp: 169,
    rating: 4.9,
    reviews: 57,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked"],
  },
  {
    ...base,
    slug: "baked-mango-cheesecake-slice",
    name: "Baked Mango Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked mango cheesecake slice",
    image: mangoCheesecake,
    price: 169,
    mrp: 169,
    rating: 4.8,
    reviews: 51,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked"],
  },
  {
    ...base,
    slug: "baked-caramel-cheesecake-slice",
    name: "Baked Caramel Cheesecake Slice",
    category: "Cheesecakes",
    categorySlug: "cheesecakes",
    note: "Baked caramel cheesecake slice",
    image: caramelBaked,
    price: 169,
    mrp: 169,
    rating: 4.8,
    reviews: 44,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Baked"],
  },
  /* ----- Tres Leches ----- */
  {
    ...base,
    slug: "alphonso-mango-tres-leches",
    name: "Alphonso Mango Tres Leches",
    category: "Tres Leches",
    categorySlug: "tres-leches",
    note: "Three-milk sponge soaked in alphonso mango",
    image: tresLechesMango,
    price: 290,
    mrp: 290,
    rating: 4.9,
    reviews: 41,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Special", "Trending"],
  },
  {
    ...base,
    slug: "thandai-tres-leches",
    name: "Thandai Tres Leches",
    category: "Tres Leches",
    categorySlug: "tres-leches",
    note: "Festive thandai soaked three-milk slice",
    image: tresLechesThandai,
    price: 199,
    mrp: 199,
    rating: 4.8,
    reviews: 32,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Special"],
  },
  {
    ...base,
    slug: "rose-tres-leches",
    name: "Rose Tres Leches",
    category: "Tres Leches",
    categorySlug: "tres-leches",
    note: "Delicate rose flavoured three-milk slice",
    image: tresLechesRose,
    price: 199,
    mrp: 199,
    rating: 4.8,
    reviews: 28,
    eggless: true,
    flavours: ["Vanilla", "Berry"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Special"],
  },
  /* ----- Mango Desserts ----- */
  {
    ...base,
    slug: "mango-tub-cake",
    name: "Mango Tub Cake",
    category: "Mango Desserts",
    categorySlug: "mango-desserts",
    note: "Fresh mango tub cake, creamy and juicy",
    image: mangoTub,
    price: 199,
    mrp: 199,
    rating: 4.8,
    reviews: 66,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["Pack of 1"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Special", "Fresh Daily"],
  },
  {
    ...base,
    slug: "mango-kunafa-bowl",
    name: "Mango Kunafa Bowl",
    category: "Mango Desserts",
    categorySlug: "mango-desserts",
    note: "Kunafa bowl loaded with mango and cream",
    image: mangoKunafaBowl,
    price: 199,
    mrp: 199,
    rating: 4.9,
    reviews: 54,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["Pack of 1"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Special"],
  },
  {
    ...base,
    slug: "mango-shake",
    name: "Mango Shake",
    category: "Beverages",
    categorySlug: "beverages",
    note: "Thick, chilled alphonso mango shake",
    image: mangoShake,
    price: 79,
    mrp: 79,
    rating: 4.8,
    reviews: 134,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "mango-pudding",
    name: "Mango Pudding",
    category: "Mango Desserts",
    categorySlug: "mango-desserts",
    note: "Silky mango pudding, chilled and smooth",
    image: mangoPudding,
    price: 79,
    mrp: 79,
    rating: 4.7,
    reviews: 61,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  /* ----- Vanilla Waffles ----- */
  {
    ...base,
    slug: "vanilla-waffle-dark-chocolate",
    name: "Vanilla Waffle with Dark Chocolate",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle topped with dark chocolate · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaDark,
    price: 100,
    mrp: 100,
    rating: 4.8,
    reviews: 47,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium", "Fresh Daily"],
  },
  {
    ...base,
    slug: "vanilla-waffle-milk-chocolate",
    name: "Vanilla Waffle with Milk Chocolate",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle topped with milk chocolate · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaMilk,
    price: 120,
    mrp: 120,
    rating: 4.8,
    reviews: 41,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium"],
  },
  {
    ...base,
    slug: "vanilla-waffle-white-chocolate",
    name: "Vanilla Waffle with White Chocolate",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle topped with white chocolate · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaWhite,
    price: 139,
    mrp: 139,
    rating: 4.8,
    reviews: 35,
    flavours: ["Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium"],
  },
  {
    ...base,
    slug: "vanilla-waffle-triple-chocolate",
    name: "Vanilla Waffle with Triple Chocolate",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle with a triple chocolate crown · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaTriple,
    price: 149,
    mrp: 149,
    rating: 4.9,
    reviews: 39,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium", "Trending"],
  },
  {
    ...base,
    slug: "vanilla-waffle-kitkat",
    name: "Vanilla Waffle with KitKat",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle loaded with KitKat · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaKitkat,
    price: 149,
    mrp: 149,
    rating: 4.9,
    reviews: 52,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Premium", "Trending"],
  },
  {
    ...base,
    slug: "vanilla-waffle-oreo",
    name: "Vanilla Waffle with Oreo",
    category: "Waffles",
    categorySlug: "waffles",
    note: "Vanilla waffle topped with crushed Oreo · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: vanillaOreo,
    price: 149,
    mrp: 149,
    rating: 4.9,
    reviews: 45,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Premium"],
  },
  /* ----- Brownies ----- */
  {
    ...base,
    slug: "brownie-with-chocolate",
    name: "Brownie with Chocolate",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Fudgy brownie with a rich chocolate pour",
    image: brownieChoc,
    price: 100,
    mrp: 100,
    rating: 4.8,
    reviews: 96,
    flavours: ["Chocolate"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium", "Fresh Daily"],
  },
  {
    ...base,
    slug: "sizzler-brownie",
    name: "Sizzler Brownie",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Sizzling hot brownie with warm chocolate",
    image: sizzlerBrownie,
    price: 150,
    mrp: 150,
    rating: 4.9,
    reviews: 74,
    flavours: ["Chocolate", "Vanilla"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium"],
  },
  {
    ...base,
    slug: "kunafa-pista-brownie",
    name: "Kunafa Pista Brownie",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Kunafa crust brownie with pistachio",
    image: pistaBrownie,
    price: 180,
    mrp: 180,
    rating: 4.9,
    reviews: 46,
    eggless: true,
    flavours: ["Chocolate", "Fruit"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium"],
  },
  {
    ...base,
    slug: "nutella-brownie",
    name: "Nutella Brownie",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Brownie crowned with a Nutella swirl",
    image: nutellaBrownie,
    price: 150,
    mrp: 150,
    rating: 4.9,
    reviews: 92,
    flavours: ["Chocolate"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Premium", "Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "nutella-kunafa-brownie",
    name: "Nutella Kunafa Brownie",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Kunafa brownie loaded with Nutella",
    image: nutellaKunafaBrownie,
    price: 180,
    mrp: 180,
    rating: 4.9,
    reviews: 43,
    flavours: ["Chocolate"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Premium", "Trending"],
  },
  {
    ...base,
    slug: "brownie-bowl",
    name: "Brownie Bowl",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Generous brownie bowl with chocolate sauce",
    image: brownieBowl,
    price: 210,
    mrp: 210,
    rating: 4.9,
    reviews: 58,
    flavours: ["Chocolate"],
    weights: ["1 Bowl"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium"],
  },
  {
    ...base,
    slug: "triple-chocolate-brownie-bowl",
    name: "Triple Chocolate Brownie Bowl",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Triple chocolate brownie bowl, over-the-top",
    image: tripleBrownieBowl,
    price: 249,
    mrp: 249,
    rating: 5.0,
    reviews: 49,
    flavours: ["Chocolate"],
    weights: ["1 Bowl"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium", "Chef Special"],
  },
  {
    ...base,
    slug: "chocolava",
    name: "Chocolava",
    category: "Brownies",
    categorySlug: "brownies",
    note: "Molten centre chocolava, baked to order",
    image: chocolavaImg,
    price: 100,
    mrp: 100,
    rating: 4.8,
    reviews: 101,
    flavours: ["Chocolate"],
    weights: ["1 Piece"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Premium", "Fresh Daily"],
  },
  /* ----- Kunafa ----- */
  {
    ...base,
    slug: "blueberry-kunafa",
    name: "Blueberry Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa topped with blueberry · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: blueberryKunafa,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 36,
    eggless: true,
    flavours: ["Berry"],
    weights: ["1 Slice"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "strawberry-kunafa",
    name: "Strawberry Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa topped with strawberry · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: strawberryKunafa,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 31,
    eggless: true,
    flavours: ["Berry"],
    weights: ["1 Slice"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "nutella-kunafa",
    name: "Nutella Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa loaded with Nutella · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: nutellaKunafa,
    price: 129,
    mrp: 129,
    rating: 4.9,
    reviews: 44,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "biscoff-kunafa",
    name: "Biscoff Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa with biscoff spread · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: biscoffKunafa,
    price: 129,
    mrp: 129,
    rating: 4.9,
    reviews: 29,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["1 Slice"],
    occasions: ["Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "chocolate-kunafa",
    name: "Chocolate Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa with a rich chocolate topping · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: chocolateKunafa,
    price: 149,
    mrp: 149,
    rating: 4.8,
    reviews: 33,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["1 Slice"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "mango-kunafa",
    name: "Mango Kunafa",
    category: "Kunafa",
    categorySlug: "kunafa",
    note: "Kunafa with fresh mango · Add-ons: ice cream +₹39, extra chocolate +₹45",
    image: kunafa,
    price: 129,
    mrp: 129,
    rating: 4.8,
    reviews: 27,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 Slice"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
];

export const categoryCount = (slug: string) =>
  menuItems.filter((m) => (slug === "all" ? true : m.categorySlug === slug)).length;

export function discountPct(m: MenuItem) {
  if (m.mrp <= m.price) return 0;
  return Math.round(((m.mrp - m.price) / m.mrp) * 100);
}

export function inr(n: number) {
  return `₹${n.toLocaleString("en-IN")}`;
}
