import ferrero from "@/assets/products/cake-ferrero.jpg";
import truffle from "@/assets/products/cake-truffle.jpg";
import blackforest from "@/assets/products/cake-blackforest.jpg";
import redvelvet from "@/assets/products/cake-redvelvet.jpg";
import tiramisu from "@/assets/products/cake-tiramisu.jpg";
import butterscotch from "@/assets/products/cake-butterscotch.jpg";
import blueberry from "@/assets/products/cake-blueberry.jpg";
import rainbow from "@/assets/products/cake-rainbow.jpg";
import cake1 from "@/assets/products/1cake.webp";
import cake2 from "@/assets/products/cake 2.webp";
import cake3 from "@/assets/products/cake3.webp";
import cake4 from "@/assets/products/cake 4.webp";
import cake5 from "@/assets/products/cake 5.webp";
import cake6 from "@/assets/products/cake 6.webp";
import cake8 from "@/assets/products/cake 8.webp";
import cake9 from "@/assets/products/cake9.webp";
import cake10 from "@/assets/products/cake 10.jpg";
import cake11 from "@/assets/products/cake 11.webp";
import cake12 from "@/assets/products/cake 12.webp";
import cake13 from "@/assets/products/cake 13.webp";
import cake15 from "@/assets/products/cake 15.webp";
import cake16 from "@/assets/products/cake 16.webp";
import cake18 from "@/assets/products/cake 18.webp";
import cake19 from "@/assets/products/cake 19.jpg";
import cake20 from "@/assets/products/cake 20.webp";
import cake21 from "@/assets/products/cake 21.webp";
import cake23 from "@/assets/products/cake 23.webp";
import cake from "@/assets/products/cake.webp";
import cake6b from "@/assets/products/cake6.webp";
import cakeke from "@/assets/products/cakeke.webp";
import assortedCake from "@/assets/products/multiple type of cake.webp";
import bite from "@/assets/products/bite.webp";
import cakeBite from "@/assets/products/cake bite 1.webp";
import cookiesImg from "@/assets/products/cookies.webp";
import cookie2 from "@/assets/products/cookie2.webp";
import coldCoffee from "@/assets/products/desi cold coffee.webp";
import drink from "@/assets/products/drink.webp";
import mangoTrifle from "@/assets/products/mongo vanulla trifle dessert bowl.webp";
import kunafa from "@/assets/products/traditional kunafa.webp";
import { ph } from "./placeholder";

export type MenuItem = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  note: string;
  image: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  delivery: "Today" | "Tomorrow";
  eggless: boolean;
  flavours: string[];
  weights: string[];
  occasions: string[];
  badges: string[];
  bestSeller?: boolean;
  newArrival?: boolean;
};

export const categoryOptions = [
  { slug: "all", label: "All Products" },
  { slug: "cakes", label: "Cakes" },
  { slug: "cupcakes", label: "Cupcakes" },
  { slug: "cookies", label: "Cookies" },
  { slug: "pastries", label: "Pastries" },
  { slug: "desserts", label: "Desserts" },
  { slug: "beverages", label: "Beverages" },
];

export const flavourOptions = ["Chocolate", "Vanilla", "Red Velvet", "Butterscotch", "Coffee", "Fruit", "Caramel", "Berry"];
export const weightOptions = ["0.5 kg", "1 kg", "1.5 kg", "2 kg", "3 kg", "Pack of 3", "Pack of 6"];
export const occasionOptions = ["Birthday", "Anniversary", "Wedding", "Kids", "Celebration"];
export const quickPicks = [
  { slug: "best-seller", label: "Best Seller" },
  { slug: "new", label: "New Arrival" },
  { slug: "discounted", label: "Discounted" },
  { slug: "today", label: "Delivery Today" },
  { slug: "stock", label: "In Stock Only" },
];

const base = {
  price: 0,
  mrp: 0,
  rating: 4.8,
  reviews: 100,
  delivery: "Today" as const,
  eggless: false,
  flavours: [] as string[],
  weights: [] as string[],
  occasions: [] as string[],
  badges: [] as string[],
};

export const menuItems: MenuItem[] = [
  {
    ...base,
    slug: "ferrero-hazelnut-cake",
    name: "Ferrero Hazelnut Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Roasted hazelnut crunch, ganache drip",
    image: ferrero,
    price: 1349,
    mrp: 1699,
    rating: 5.0,
    reviews: 512,
    flavours: ["Chocolate"],
    weights: ["1 kg", "1.5 kg", "2 kg", "3 kg"],
    occasions: ["Birthday", "Anniversary", "Wedding", "Celebration"],
    badges: ["Best Seller", "Limited Edition"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "chocolate-truffle-cake",
    name: "Chocolate Truffle Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Belgian ganache, silk-soft sponge",
    image: truffle,
    price: 899,
    mrp: 1199,
    rating: 4.9,
    reviews: 428,
    eggless: true,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Best Seller", "Chef Special"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "black-forest-cake",
    name: "Black Forest Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Kirsch cherries, dark chocolate flakes",
    image: blackforest,
    price: 849,
    mrp: 1049,
    rating: 4.8,
    reviews: 376,
    delivery: "Tomorrow",
    flavours: ["Chocolate", "Fruit"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "red-velvet-cherry-cake",
    name: "Red Velvet Cherry Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Cream cheese clouds, morello cherries",
    image: redvelvet,
    price: 949,
    mrp: 1249,
    rating: 4.8,
    reviews: 312,
    eggless: true,
    flavours: ["Red Velvet"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Anniversary", "Kids"],
    badges: ["Trending", "Fresh Today"],
  },
  {
    ...base,
    slug: "tiramisu-cake",
    name: "Classic Tiramisu",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Espresso soak, mascarpone velvet",
    image: tiramisu,
    price: 999,
    mrp: 1199,
    rating: 4.8,
    reviews: 231,
    flavours: ["Coffee"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Anniversary", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "butterscotch-praline-cake",
    name: "Butterscotch Praline Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Golden caramel drip, praline crunch",
    image: butterscotch,
    price: 799,
    mrp: 999,
    rating: 4.7,
    reviews: 208,
    eggless: true,
    flavours: ["Butterscotch", "Caramel"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Eggless", "100% Handmade"],
  },
  {
    ...base,
    slug: "blueberry-cheesecake",
    name: "Blueberry Cheesecake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Baked New York style, wild berries",
    image: blueberry,
    price: 1099,
    mrp: 1399,
    rating: 4.9,
    reviews: 189,
    flavours: ["Fruit"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Anniversary", "Wedding", "Celebration"],
    badges: ["Chef Special", "Limited Edition"],
  },
  {
    ...base,
    slug: "pastel-rainbow-cake",
    name: "Pastel Rainbow Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Six pastel layers, vanilla bean cream",
    image: rainbow,
    price: 1249,
    mrp: 1549,
    rating: 4.7,
    reviews: 142,
    delivery: "Tomorrow",
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["New", "Eggless"],
    newArrival: true,
  },
  {
    ...base,
    slug: "classic-vanilla-dream",
    name: "Classic Vanilla Dream",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Madagascar vanilla sponge with mascarpone cream",
    image: cake1,
    price: 950,
    mrp: 1100,
    rating: 4.8,
    reviews: 356,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "rose-petal-delight",
    name: "Rose Petal Delight",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Floral buttercream, delicate rose drizzle",
    image: cake2,
    price: 899,
    mrp: 1149,
    rating: 4.8,
    reviews: 187,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "cream-cascade-cake",
    name: "Cream Cascade Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Soft cream layers with a glossy cascade",
    image: cake3,
    price: 799,
    mrp: 999,
    rating: 4.7,
    reviews: 124,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "choco-drip-cake",
    name: "Choco Drip Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Rich chocolate drip over silky sponge",
    image: cake4,
    price: 999,
    mrp: 1249,
    rating: 4.9,
    reviews: 268,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Best Seller", "Chef Special"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "berry-bloom-cake",
    name: "Berry Bloom Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Fresh berries crowned on vanilla cream",
    image: cake5,
    price: 1099,
    mrp: 1399,
    rating: 4.8,
    reviews: 156,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg", "2 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "buttercream-bliss-cake",
    name: "Buttercream Bliss Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Whipped buttercream, soft vanilla base",
    image: cake6,
    price: 899,
    mrp: 1099,
    rating: 4.8,
    reviews: 143,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "caramel-crown-cake",
    name: "Caramel Crown Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Golden caramel glaze with a rich base",
    image: cake8,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 98,
    eggless: true,
    flavours: ["Caramel"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "velvet-swirl-cake",
    name: "Velvet Swirl Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Marbled swirl finish on cream layers",
    image: cake9,
    price: 849,
    mrp: 1049,
    rating: 4.7,
    reviews: 112,
    flavours: ["Vanilla", "Berry"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "silk-cake-classic",
    name: "Silk Cake Classic",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Feather-light sponge with silk icing",
    image: cake10,
    price: 799,
    mrp: 999,
    rating: 4.7,
    reviews: 176,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Eggless", "Fresh Today"],
  },
  {
    ...base,
    slug: "garden-party-cake",
    name: "Garden Party Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Bright blooms and cheerful cream swirls",
    image: cake11,
    price: 1099,
    mrp: 1399,
    rating: 4.9,
    reviews: 132,
    flavours: ["Vanilla", "Fruit"],
    weights: ["1 kg", "1.5 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "frosted-fancy-cake",
    name: "Frosted Fancy Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Piped frosting, party-perfect finish",
    image: cake12,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 88,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "royal-rose-cake",
    name: "Royal Rose Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Rose-topped elegance in soft pastels",
    image: cake13,
    price: 1149,
    mrp: 1449,
    rating: 4.9,
    reviews: 76,
    eggless: true,
    flavours: ["Vanilla", "Berry"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Anniversary", "Wedding", "Celebration"],
    badges: ["Signature", "Chef Special"],
  },
  {
    ...base,
    slug: "swirl-dream-cake",
    name: "Swirl Dream Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Tall cream swirls, soft baked layers",
    image: cake15,
    price: 899,
    mrp: 1099,
    rating: 4.7,
    reviews: 94,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "hazelnut-paradise-cake",
    name: "Hazelnut Paradise Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Nutty crunch with a smooth choco glaze",
    image: cake16,
    price: 1049,
    mrp: 1299,
    rating: 4.8,
    reviews: 118,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Trending"],
  },
  {
    ...base,
    slug: "choco-nut-delight",
    name: "Choco Nut Delight",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Belgian chocolate with toasted nuts",
    image: cake18,
    price: 949,
    mrp: 1199,
    rating: 4.8,
    reviews: 202,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "vanilla-bean-cake",
    name: "Vanilla Bean Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Real vanilla bean speckle, cloud cream",
    image: cake19,
    price: 849,
    mrp: 1049,
    rating: 4.7,
    reviews: 164,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["Eggless"],
  },
  {
    ...base,
    slug: "petite-cake-slice",
    name: "Petite Cake Slice",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Perfect single-serving layered slice",
    image: cake20,
    price: 199,
    mrp: 249,
    rating: 4.7,
    reviews: 240,
    eggless: true,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "berry-cheer-cake",
    name: "Berry Cheer Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Berry-dotted buttercream, bright finish",
    image: cake21,
    price: 999,
    mrp: 1249,
    rating: 4.8,
    reviews: 86,
    flavours: ["Berry", "Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "confetti-fun-cake",
    name: "Confetti Fun Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Celebration sprinkles on vanilla cream",
    image: cake23,
    price: 899,
    mrp: 1099,
    rating: 4.7,
    reviews: 74,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Fresh Today"],
  },
  {
    ...base,
    slug: "bakers-choice-cake",
    name: "Baker's Choice Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "The counter favourite, baked fresh daily",
    image: cake,
    price: 899,
    mrp: 1099,
    rating: 4.8,
    reviews: 321,
    eggless: true,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["Best Seller", "100% Handmade"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "double-choco-cake",
    name: "Double Choco Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Two-layer cocoa indulgence, glossy top",
    image: cake6b,
    price: 979,
    mrp: 1229,
    rating: 4.8,
    reviews: 145,
    flavours: ["Chocolate"],
    weights: ["0.5 kg", "1 kg", "1.5 kg"],
    occasions: ["Birthday", "Anniversary"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "house-special-cake",
    name: "House Special Cake",
    category: "Cakes",
    categorySlug: "cakes",
    note: "Signature recipe, creamy and light",
    image: cakeke,
    price: 949,
    mrp: 1149,
    rating: 4.8,
    reviews: 98,
    eggless: true,
    flavours: ["Vanilla"],
    weights: ["0.5 kg", "1 kg"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Signature"],
  },
  {
    ...base,
    slug: "celebration-assortment",
    name: "Celebration Assortment",
    category: "Cakes",
    categorySlug: "cakes",
    note: "A platter of our finest designs to share",
    image: assortedCake,
    price: 1499,
    mrp: 1899,
    rating: 4.9,
    reviews: 210,
    flavours: ["Vanilla", "Chocolate", "Fruit"],
    weights: ["2 kg"],
    occasions: ["Birthday", "Celebration", "Wedding"],
    badges: ["Best Seller", "Limited Edition"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "berry-bliss-cupcakes",
    name: "Berry Bliss Cupcakes",
    category: "Cupcakes",
    categorySlug: "cupcakes",
    note: "Vanilla bean cupcakes, mixed-berry swiss meringue",
    image: bite,
    price: 220,
    mrp: 260,
    rating: 4.8,
    reviews: 96,
    flavours: ["Vanilla", "Berry"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Kids"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "mini-cake-bites",
    name: "Mini Cake Bites",
    category: "Cupcakes",
    categorySlug: "cupcakes",
    note: "Bite-sized bakes with silky cream tops",
    image: cakeBite,
    price: 299,
    mrp: 349,
    rating: 4.7,
    reviews: 84,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Kids", "Celebration"],
    badges: ["New", "Fresh Daily"],
    newArrival: true,
  },
  {
    ...base,
    slug: "salted-caramel-cookie",
    name: "Salted Caramel Cookie",
    category: "Cookies",
    categorySlug: "cookies",
    note: "Chewy centre, crisp edges, gooey caramel",
    image: cookie2,
    price: 120,
    mrp: 150,
    rating: 4.7,
    reviews: 140,
    flavours: ["Chocolate", "Caramel"],
    weights: ["Pack of 3"],
    occasions: ["Kids", "Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "classic-cookie-box",
    name: "Classic Cookie Box",
    category: "Cookies",
    categorySlug: "cookies",
    note: "Buttery classics, baked golden and crisp",
    image: cookiesImg,
    price: 349,
    mrp: 420,
    rating: 4.8,
    reviews: 165,
    flavours: ["Vanilla", "Chocolate"],
    weights: ["Pack of 6"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "mango-vanilla-trifle",
    name: "Mango Vanilla Trifle",
    category: "Desserts",
    categorySlug: "desserts",
    note: "Layered mango, vanilla cream and sponge",
    image: mangoTrifle,
    price: 349,
    mrp: 420,
    rating: 4.8,
    reviews: 92,
    eggless: true,
    flavours: ["Fruit", "Vanilla"],
    weights: ["Pack of 1"],
    occasions: ["Birthday", "Celebration"],
    badges: ["Fresh Daily", "Eggless"],
  },
  {
    ...base,
    slug: "traditional-kunafa",
    name: "Traditional Kunafa",
    category: "Desserts",
    categorySlug: "desserts",
    note: "Crispy semolina, sweet cheese pull, syrup",
    image: kunafa,
    price: 449,
    mrp: 540,
    rating: 4.9,
    reviews: 78,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "desi-cold-coffee",
    name: "Desi Cold Coffee",
    category: "Beverages",
    categorySlug: "beverages",
    note: "Frothy, chilled, slow-brewed classic",
    image: coldCoffee,
    price: 180,
    mrp: 220,
    rating: 4.8,
    reviews: 210,
    flavours: ["Coffee"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily", "Best Seller"],
    bestSeller: true,
  },
  {
    ...base,
    slug: "signature-cold-drink",
    name: "Signature Cold Drink",
    category: "Beverages",
    categorySlug: "beverages",
    note: "House blend iced treat, served chilled",
    image: drink,
    price: 199,
    mrp: 249,
    rating: 4.7,
    reviews: 134,
    flavours: ["Coffee", "Vanilla"],
    weights: ["Pack of 1"],
    occasions: ["Celebration"],
    badges: ["New"],
    newArrival: true,
  },
  {
    ...base,
    slug: "almond-croissant",
    name: "Almond Croissant",
    category: "Pastries",
    categorySlug: "pastries",
    note: "Twice-baked, frangipane filled, snowed with icing",
    image: ph("Almond Croissant", "#e8a598", "#d9a05f"),
    price: 180,
    mrp: 220,
    rating: 4.8,
    reviews: 210,
    flavours: ["Vanilla"],
    weights: ["Pack of 3"],
    occasions: ["Celebration"],
    badges: ["Fresh Daily"],
  },
  {
    ...base,
    slug: "raspberry-pistachio-tart",
    name: "Raspberry Pistachio Tart",
    category: "Desserts",
    categorySlug: "desserts",
    note: "Pistachio shell, silky raspberry curd, rose finish",
    image: ph("Raspberry Tart", "#6b3f23", "#e8a598"),
    price: 380,
    mrp: 450,
    rating: 4.9,
    reviews: 78,
    flavours: ["Fruit", "Vanilla"],
    weights: ["Pack of 3"],
    occasions: ["Anniversary", "Celebration"],
    badges: ["Chef Special"],
  },
  {
    ...base,
    slug: "saffron-pistachio-slice",
    name: "Saffron Pistachio Slice",
    category: "Desserts",
    categorySlug: "desserts",
    note: "Bespoke saffron milk cake, roasted pistachio crunch",
    image: ph("Saffron Slice", "#3a2517", "#c9a24b"),
    price: 1200,
    mrp: 1400,
    rating: 4.9,
    reviews: 54,
    eggless: true,
    flavours: ["Fruit"],
    weights: ["1 kg"],
    occasions: ["Wedding", "Anniversary", "Celebration"],
    badges: ["Bespoke"],
  },
];

export const categoryCount = (slug: string) =>
  menuItems.filter((m) => (slug === "all" ? true : m.categorySlug === slug)).length;

export function discountPct(m: MenuItem) {
  if (m.mrp <= m.price) return 0;
  return Math.round(((m.mrp - m.price) / m.mrp) * 100);
}

export function inr(n: number) {
  return `₹${n.toLocaleString("en-IN")}`;
}
